### PR TITLE
Update codebase to Python 3

### PR DESCRIPTION
**Pull request by nemzyxt**
This commit updates the codebase to use Python 3 instead of Python 2 . It includes changes to syntax, and some packages versions in order for the project to be fully compatible with Python 3 . The changes were made in accordance with best practices for porting code from Python 2 to Python 3

### CODE REVIEW

**Comment by hasturo** [comment]
Great effort but didnt repaired my failed installation on Parrot OS. Thank you for trying anyways!

**Comment by RavageHunter** [comment]
Umm... How do I download this (I am new to all of this)

**Comment by RavageHunter** [comment]
btw it showed some errors, I hope you could fix those

**Comment by nemzyxt** [comment]
@hasturo , @RavageHunter you can please consider sharing more details about the error messages you get
Probably create an issue too ?

**Pull request closed without merging**
