### PR TITLE
Fix for issue 105 -- more robust IP and hostname validation

### PR DESCRIPTION
**Pull request by bbeale**
Added a regex to look for hostname and IPV4 patterns. If this first check passes, then the `ipaddress` module from the standard library is used to validate the IP address. If a hostname is detected instead of an IP address, it will try to get the fully qualified domain name. Keeping within the standard library, `socket.getfqdn` was used for this step. Let me know if you think the FQDN part might be overkill. 

I added this for options 1 and 7, which prompt the user for an IP address or domain. I left out the domain part for option 7.

### CODE REVIEW

**Comment by drwetter** [comment]
Why the F^Wheck was this automatically closed?

Wondering whether this project is still maintained.

**Comment by bbeale** [comment]
Clearly I wasn't quick enough with my edit to avoid getting auto closed.

He did respond to one of my other threads though @drwetter, I think he's busy but getting to them slowly but surely.

**Comment by drwetter** [comment]
Ok but why is the bot enabled if he/she cannot get to it atm?

**Comment by drwetter** [comment]
Is this project still alive?

**Comment by bbeale** [comment]
Doesn't look like it @drwetter. It can always be reopened if the maintainer wants this PR, but I'm not going to worry about it anymore until that happens.

**Comment by tcstool** [comment]
I am the original creator of this tool back in 2014 and turned it over to
another maintainer a few years ago due to time constraints I had.  I would
love to see the project keep going but I don't think the current maintainer
has done a good job devoting time to it.  It really needs a complete
overhaul and rewrite.

**Pull request closed without merging**
